#!/usr/bin/env bash

##########################
### SCRIPT INFORMATION ###
##########################

# Name: ewwlo-toggle
# Dependencies: eww, ewwlogout
# Description: Toggle logout screen

if eww active-windows | grep ewwlogout >/dev/null; then
  eww close ewwlogout
else
  eww open ewwlogout
fi
