#!/usr/bin/env bash

##########################
### SCRIPT INFORMATION ###
##########################

# Name: rebar
# Dependencies: waybar
# Description: Reload WayBar Config

pkill -f waybar --signal USR2
