#!/usr/bin/env bash

##########################
### SCRIPT INFORMATION ###
##########################

# Name: musepaper
# Dependencies: tauon, hyprwinwrap (hypr-plugin), playerctl, kitty
# Description: Script for showing album art and song info on desktop

# Recommended Font Size 16

BG="\e[40m"
RESET="\e[0m"

control_c() {
  clear
  tput cnorm
  exit
}

repeat() {
  for i in $(seq 1 $1); do echo -n " "; done
}

compare() {
  local RESULT=$(expr $1 - $2)
  echo $RESULT
}

max_len() {
  local ARRAY="$1
$2
$3"
  IFS=$"\n" readarray -t SORT <<<"$(sort -n <<<"${ARRAY[*]}")"
  unset IFS

  echo "${SORT[-1]}"
}

trap control_c SIGINT
tput civis

mainloop() {
  while true; do
    STATUS=$(playerctl -p tauon status)
    COVER=$(playerctl -p tauon metadata --format "{{mpris:artUrl}}")
    TITLE=$(playerctl -p tauon metadata --format "{{title}}")
    ARTIST=$(playerctl -p tauon metadata --format "{{artist}}")
    ALBUM="[$(playerctl -p tauon metadata --format "{{album}}")]"

    TITLE_LEN=${#TITLE}
    ARTIST_LEN=${#ARTIST}
    ALBUM_LEN=${#ALBUM}
    MAX_LEN=$(max_len "$TITLE_LEN" "$ARTIST_LEN" "$ALBUM_LEN")

    if [ "$STATUS" = "Playing" ]; then
      kitten icat --place 25x25@5x3 $COVER

      echo
      echo
      repeat 33
      echo -ne "$BG  "
      repeat $MAX_LEN
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  $TITLE"
      repeat $(compare $MAX_LEN $TITLE_LEN)
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  "
      repeat $MAX_LEN
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  $ARTIST"
      repeat $(compare $MAX_LEN $ARTIST_LEN)
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  "
      repeat $MAX_LEN
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  $ALBUM"
      repeat $(compare $MAX_LEN $ALBUM_LEN)
      echo -ne "  $RESET\n"

      repeat 33
      echo -ne "$BG  "
      repeat $MAX_LEN
      echo -ne "  $RESET\n"
    else
      clear
    fi

    sleep 5

    if [ ! "$(playerctl -p tauon metadata --format "{{title}}")" = "$TITLE" ] || [ ! "$(playerctl -p tauon metadata --format "{{artist}}")" = "$ARTIST" ] || [ ! "[$(playerctl -p tauon metadata --format "{{album}}")]" = "$ALBUM" ]; then
      clear
    fi

  done
}

clear
mainloop
clear
