#!/usr/bin/env bash

# temporary wallpaper location
WALL="$HOME/.config/hypr/temp-wall.jpg"

# replace temp with chosen wallpaper
magick "$1" "$WALL"

# hyprpaper
hyprctl hyprpaper unload all
hyprctl hyprpaper preload "$WALL"
hyprctl hyprpaper wallpaper ",$WALL"
# hellwal -i "$WALL" -m --no-cache
