#!/usr/bin/env bash

declare -A WC_LIST

LOC=$(curl http://ip-api.com/json?fields=lat,lon,city,country -s | jq -c)

LAT=$(echo "$LOC" | jq -r '.lat' | awk '{printf "%.2f",$1}')
LONG=$(echo "$LOC" | jq -r '.lon' | awk '{printf "%.2f",$1}')
CITY=$(echo "$LOC" | jq -r '.city' | awk '{printf "%s",$1}')
COUNTRY=$(echo "$LOC" | jq -r '.country' | awk '{printf "%s",$1}')

WTHR_API=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=$LAT&longitude=$LONG&current=temperature_2m,relative_humidity_2m,precipitation,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day,weather_code" | jq -c)

TIME="$(echo "$WTHR_API" | jq -r '.current.time' | awk '{split($1, time, "T"); printf "%s %s",time[1],time[2]}')"
TEMP="$(echo "$WTHR_API" | jq -r '.current.temperature_2m')$(echo "$WTHR_API" | jq -r '.current_units.temperature_2m')"
HUMID="$(echo "$WTHR_API" | jq -r '.current.relative_humidity_2m')%"
PREC="$(echo "$WTHR_API" | jq -r '.current.precipitation') $(echo "$WTHR_API" | jq -r '.current_units.precipitation')"
CLOUD="$(echo "$WTHR_API" | jq -r '.current.cloud_cover')%"
WIND_S="$(echo "$WTHR_API" | jq -r '.current.wind_speed_10m') $(echo "$WTHR_API" | jq -r '.current_units.wind_speed_10m')"
WIND_G="$(echo "$WTHR_API" | jq -r '.current.wind_gusts_10m') $(echo "$WTHR_API" | jq -r '.current_units.wind_gusts_10m')"

WIND_ARR=(
  "N"
  "NE"
  "E"
  "SE"
  "S"
  "SW"
  "W"
  "NW"
)
WIND_DIR="$(echo "$WTHR_API" | jq -r '.current.wind_direction_10m')"
WIND_DIR_LET="$(echo "${WIND_ARR[$(echo "$WIND_DIR" | awk '{print int(($1 / 45) % 8 )}')]}")"

IS_DAY="$(echo "$WTHR_API" | jq -r '.current.is_day')"
WC="$(echo "$WTHR_API" | jq -r '.current.weather_code')"

WC_LIST=(
  ["0_0"]="󰖔 "
  ["0_1"]="󰖙 "
  ["1_0"]="󰖔 "
  ["1_1"]="󰖙 "
  ["2"]="󰖐 "
  ["3"]="󰖐 "
  ["45"]="󰖑 "
  ["48"]="󰖑 "
  ["51"]="󰖗 "
  ["53"]="󰖗 "
  ["55"]="󰖗 "
  ["56"]="󰙿 "
  ["57"]="󰙿 "
  ["61"]="󰖖 "
  ["63"]="󰖖 "
  ["65"]="󰖖 "
  ["66"]="󰙿 "
  ["67"]="󰙿 "
  ["71"]="󰖘 "
  ["73"]="󰖘 "
  ["75"]="󰼶 "
  ["77"]="󰖒 "
  ["80"]="󰖖 "
  ["81"]="󰖖 "
  ["82"]="󰖖 "
  ["85"]="󰼶 "
  ["86"]="󰼶 "
  ["95"]="󰖓 "
  ["96"]="󰖓 "
  ["99"]="󰖓 "
)

WI="$(echo "${WC_LIST["$(echo "$WC $IS_DAY" | awk '{if ($1 <= 1) {printf "%s_%s",$1,$2} else {printf "%s",$1}}')"]}")"

echo "{'text': '$TEMP <big>$WI</big>', 'tooltip': '\tWeather\n\n$CITY, $COUNTRY\nTime: $TIME\n\nTemperature: $TEMP\nHumidity: $HUMID\nPrecipitaion: $PREC\nCloud Cover: $CLOUD\nWind Direct: $WIND_DIR_LET\nWind Speed: $WIND_S\nWind Gusts: $WIND_G'}" | sed -e "s/'/\"/g" | jq -c
