[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "korganizer"
terminal = "kitty"

[debug]
try_suppress_errors     =   false                                   
try_suppress_warnings   =   false                                  
app_paths               =   ["~/.local/share/applications/", "/usr/share/applications/", "/usr/local/share/applications/"]        

[units]
lengths                 =   "meter"
weights                 =   "kg"
volumes                 =   "l"
temperatures            =   "C"

[appearance]
width                   =   900                                       
height                  =   593                                       
gsk_renderer            =   "cairo"                                   
recolor_icons           =   false                                     
icon_paths              =   [ "~/.config/sherlock/icons"]             
icon_size               =   32                                        
search_icon             =   false                                        
use_base_css            =   false
status_bar              =   true

[behavior]
caching                 =   true                                    
cache                   =   "~/.cache/sherlock_desktop_cache.json"  
daemonize               =   false                                  
animation               =   true                                    
global_prefix           =   ""                                   
global_flags            =   ""                                    

[binds]
prev                    =   "None"                                  
next                    =   "None"                                  
modifier                =   "control"                               

[files]
fallback                =   "~/.config/sherlock/fallback.json"
css                     =   "~/.config/sherlock/main.css"
alias                   =   "~/.config/sherlock/sherlock_alias.json"
ignore                  =   "~/.config/sherlock/sherlockignore"
