#!/usr/bin/env bash

splitcmd() {
  IFS=" " read -ra VOL <<<"$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
  VOLUME=$(echo "print(round(${VOL[1]} * 100))" | python3)
  echo "$VOLUME"
}

if ! eww active-windows | grep toastvolume >>/dev/null; then eww open toastvolume; fi

while true; do
  TEST1=$(splitcmd)
  sleep 3
  TEST2=$(splitcmd)
  if [ "$TEST1" = "$TEST2" ]; then
    eww close toastvolume
    break
  fi
done
