#!/usr/bin/env bash

declare -A WIF

START="$(awk '/wlan0/ {print $2, $10}' <(cat /proc/net/dev)) $(awk '/enp3s0/ {print $2, $10}' <(cat /proc/net/dev))"
sleep 1
END="$(awk '/wlan0/ {print $2, $10}' <(cat /proc/net/dev)) $(awk '/enp3s0/ {print $2, $10}' <(cat /proc/net/dev))"
WIF=(
  ["NET_DL"]="$(echo "$END $START" | awk '{print ($1 - $5) + ($3 - $7)}' | awk '{if ($1 >= 1073741824) {printf "%.2f %s", ($1 / 1073741824), "GiB/s"} else if ($1 >= 1048576) {printf "%.2f %s", ($1 / 1048576), "MiB/s"} else if ($1 >= 1024) {printf "%.2f %s", ($1 / 1024), "kiB/s"} else {printf "%.2f %s", $1, "B/s"}}' | awk '{if ($1 % 1 == 0) {printf "%.0f %s", $1, $2} else {print $1, $2}}')"
  ["NET_UP"]="$(echo "$END $START" | awk '{print ($2 - $6) + ($4 - $8)}' | awk '{if ($1 >= 1073741824) {printf "%.2f %s", ($1 / 1073741824), "GiB/s"} else if ($1 >= 1048576) {printf "%.2f %s", ($1 / 1048576), "MiB/s"} else if ($1 >= 1024) {printf "%.2f %s", ($1 / 1024), "kiB/s"} else {printf "%.2f %s", $1, "B/s"}}' | awk '{if ($1 % 1 == 0) {printf "%.0f %s", $1, $2} else {print $1, $2}}')"
  ["TOTAL_DL"]="$(echo "$END" | awk '{print $1 + $3}' | awk '{if ($1 >= 1073741824) {printf "%.2f %s", ($1 / 1073741824), "GiB"} else if ($1 >= 1048576) {printf "%.2f %s", ($1 / 1048576), "MiB"} else if ($1 >= 1024) {printf "%.2f %s", ($1 / 1024), "kiB"} else {printf "%.2f %s", $1, "B"}}' | awk '{if ($1 % 1 == 0) {printf "%.0f %s", $1, $2} else {print $1, $2}}')"
  ["TOTAL_UP"]="$(echo "$END" | awk '{print $2 + $4}' | awk '{if ($1 >= 1073741824) {printf "%.2f %s", ($1 / 1073741824), "GiB"} else if ($1 >= 1048576) {printf "%.2f %s", ($1 / 1048576), "MiB"} else if ($1 >= 1024) {printf "%.2f %s", ($1 / 1024), "kiB"} else {printf "%.2f %s", $1, "B"}}' | awk '{if ($1 % 1 == 0) {printf "%.0f %s", $1, $2} else {print $1, $2}}')"
)

echo "{'tooltip': 'Current Speed\n\n ${WIF["NET_DL"]}\n ${WIF["NET_UP"]}\n───────────────\nTotal Data Used\n\n ${WIF["TOTAL_DL"]}\n ${WIF["TOTAL_UP"]}'}" | sed -e "s/'/\"/g" | jq -c
