#!/usr/bin/env bash

source ~/.cache/hellwal/ansi-colors-hex.sh

# Date
DATE=$(date +"%y/%m/%d")

# Tooltip
CALENDAR=$(cal -m)
MONTH="$(echo "$CALENDAR" | sed "1q;d")"
WEEKDAYS="$(echo "$CALENDAR" | sed "2q;d")"
DAYS="$(echo "$CALENDAR" | tail -n 6 | head -n 5)"
TODAY="$(date +"%-d")"

IFS=$'\n' read -rd '' -a DAYS_A <<<"$DAYS"
unset IFS

TOOLTIP="<span color=''$COLOR_5''>$MONTH</span>\n\n<span color=''$COLOR_6''>$WEEKDAYS</span>\n"

for i in "${DAYS_A[@]}"; do
  i=$(echo "$i" | sed "s/\ $TODAY\ /\ <\/span><span color=''$COLOR_2''>$TODAY<\/span><span color=''$COLOR_7''>\ /g")
  TOOLTIP+="<span color=''$COLOR_7''>$i</span>\n"
done

TOOLTIP=${TOOLTIP::-2}

echo "{'text': '$DATE', 'tooltip': '$TOOLTIP'}" | sed "s/'/\"/g" | sed "s/\"\"/'/g" | jq -c
