return {
	custom = {
		black = "#444444",
		bg0 = "#%%color0.hex%%",
		bg1 = "#%%color8.hex%%",
		bg2 = "#%%color9.hex%%",
		bg3 = "#%%color10.hex%%",
		bg_d = "#%%background%%",
		bg_blue = "#61afef",
		bg_yellow = "#e8c88c",
		fg = "#%%color7.hex%%",
		purple = "#C843FF",
		green = "#81FF1E",
		orange = "#cc9057",
		blue = "#27D8FF",
		yellow = "#FFE836",
		cyan = "#43FFEF",
		red = "#ff5353",
		grey = "#A1A1A1",
		light_grey = "#E1E1E1",
		dark_cyan = "#00CEBD",
		dark_red = "#ff0000",
		dark_yellow = "#DCC300",
		dark_purple = "#A800ED",
		diff_add = "#%%color2.hex%%",
		diff_delete = "#%%color3.hex%%",
		diff_change = "#%%color5.hex%%",
		diff_text = "#%%color7.hex%%",
	},
}
