#!/usr/bin/env bash

# This script defines just a mode for rofi instead of being a self-contained
# executable that launches rofi by itself. This makes it more flexible than
# running rofi inside this script as now the user can call rofi as one pleases.
# For instance:
#
#   rofi -show powermenu -modi powermenu:./rofi-power-menu
#
# See README.md for more information.

set -e
set -u

# All supported choices
all=(shutdown reboot suspend logout lockscreen)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[lockscreen]="Lock"
texts[logout]="Logout"
texts[suspend]="Suspend"
texts[reboot]="Reboot"
texts[shutdown]="Shutdown"

declare -A icons
icons[lockscreen]="pow-lock"
icons[logout]="pow-log-out"
icons[suspend]="pow-suspend"
icons[reboot]="pow-reboot"
icons[shutdown]="pow-shut-down"
icons[cancel]="pow-cancel"

declare -A actions
actions[lockscreen]="hyprlock"
actions[logout]="kill -9 -1"
actions[suspend]="systemctl suspend"
actions[reboot]="systemctl reboot"
actions[shutdown]="systemctl poweroff"

# By default, ask for confirmation for actions that are irreversible
confirmations=(reboot shutdown logout suspend)

function write_message {
  text="$2\0icon\x1f$1"
  echo -n "$text"
}

function print_selection {
  echo -e "$1" | $(
    read -r -d '' entry
    echo "echo $entry"
  )
}

declare -A messages
declare -A confirmationMessages
for entry in "${all[@]}"; do
  messages[$entry]=$(write_message "${icons[$entry]}" "${texts[$entry]^}")
done
for entry in "${all[@]}"; do
  # Add zero-width space character (\u200b) to icon to ensure confirmation-
  # and regular messages never collide.
  confirmationMessages[$entry]=$(write_message "${icons[$entry]}" "Yes, ${texts[$entry]}")
done
confirmationMessages[cancel]=$(write_message "${icons[cancel]}" "No, Cancel")

if [ $# -gt 0 ]; then
  # If arguments given, use those as the selection
  selection="${@}"
else
  # Otherwise, use the CLI passed choice if given
  if [ -n "${selectionID+x}" ]; then
    selection="${messages[$selectionID]}"
  fi
fi

# Don't allow custom entries
echo -e "\0no-custom\x1ftrue"
# Use markup
echo -e "\0markup-rows\x1ftrue"

if [ -z "${selection+x}" ]; then
  echo -e "\0prompt\x1f Power"
  for entry in "${show[@]}"; do
    echo -e "${messages[$entry]}\0icon\x1f${icons[$entry]}"
  done
else
  for entry in "${show[@]}"; do
    if [ "$selection" = "$(print_selection "${messages[$entry]}")" ]; then
      # Check if the selected entry is listed in confirmation requirements
      for confirmation in "${confirmations[@]}"; do
        if [ "$entry" = "$confirmation" ]; then
          # Ask for confirmation
          echo -e "\0prompt\x1fAre you sure"
          echo -e "${confirmationMessages[$entry]}\0icon\x1f${icons[$entry]}"
          echo -e "${confirmationMessages[cancel]}\0icon\x1f${icons[cancel]}"
          exit 0
        fi
      done
      # If not, then no confirmation is required, so mark confirmed
      selection=$(print_selection "${confirmationMessages[$entry]}")
    fi
    if [ "$selection" = "$(print_selection "${confirmationMessages[$entry]}")" ]; then
      ${actions[$entry]}
      exit 0
    fi
    if [ "$selection" = "$(print_selection "${confirmationMessages[cancel]}")" ]; then
      # Do nothing
      exit 0
    fi
  done
  # The selection didn't match anything, so raise an error
  echo "Invalid selection: $selection" >&2
  exit 1
fi
